version: 5.5.0.4
type: payment
authorName: 'Ilya I'
moduleName: 'CloverPayments'
description: 'Clover integration'
minorRequiredCoreVersion: 0 
dependsOn: {  }
incompatibleWith: {  }
showSettingsForm: true
canDisable: true